USE [DB_MIS]
GO

/****** Object:  Table [dbo].[TBL_WEB_RH_COMBO_ATIVIDADE_ATIVA]    Script Date: 15/04/2025 17:05:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_WEB_RH_COMBO_ATIVIDADE_ATIVA](
	[NR_ATIVIDADE] [char](9) NOT NULL,
	[NM_CARTEIRA] [varchar](8000) NULL
) ON [PRIMARY]
GO

