USE [DB_MIS]
GO

/****** Object:  Table [dbo].[TBL_WEB_COLABORADOR_DADOS]    Script Date: 15/04/2025 17:04:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_WEB_COLABORADOR_DADOS](
	[NR_COLABORADOR] [int] IDENTITY(1,1) NOT NULL,
	[NR_EMPRESA] [char](4) NULL,
	[NR_MATRICULA] [nvarchar](20) NULL,
	[NR_CATRACA_GTZ] [int] NULL,
	[NR_CATRACA_MTZ] [int] NULL,
	[DT_ADMISSAO] [datetime] NULL,
	[DT_DEMISSAO] [datetime] NULL,
	[DT_NASCIMENTO] [datetime] NULL,
	[NM_COLABORADOR] [varchar](300) NULL,
	[NR_CPF] [bigint] NOT NULL,
	[TP_SEXO] [char](1) NULL,
	[NR_DDD01] [tinyint] NULL,
	[NR_TELEFONE01] [numeric](9, 0) NULL,
	[NR_DDD02] [tinyint] NULL,
	[NR_TELEFONE02] [numeric](10, 0) NULL,
	[NR_RAMAL] [numeric](4, 0) NULL,
	[NM_EMAIL] [varchar](100) NULL,
	[TP_FUNCAO] [tinyint] NULL,
	[TP_GESTOR] [char](1) NULL,
	[NR_GESTOR] [int] NULL,
	[NR_FILIAL] [char](1) NULL,
	[NR_FUNCAO_RH] [nvarchar](10) NULL,
	[NR_ATIVIDADE_RH] [nvarchar](10) NULL,
	[NR_JORNADA_TRAB_RH] [nvarchar](10) NULL,
	[TP_ACESSO_SISTEMA] [varchar](20) NULL,
	[NM_SENHA] [varchar](100) NULL,
	[NR_COORDENADOR] [int] NULL,
	[NR_SUPERVISOR] [int] NULL,
	[NM_EQUIPE] [varchar](50) NULL,
	[NR_OLOS] [int] NULL,
	[NM_LOGIN_OLOS] [varchar](50) NULL,
	[NR_OLOS_MTZ] [int] NULL,
	[NM_LOGIN_OLOS_MTZ] [varchar](50) NULL,
	[TP_PAVIMENTO] [char](1) NULL,
	[TP_TURNO] [char](1) NULL,
	[TP_STATUS] [tinyint] NULL,
	[DT_STATUS01] [datetime] NULL,
	[DT_STATUS02] [datetime] NULL,
	[NM_OBSERVACAO] [varchar](max) NULL,
	[NR_USUARIO_INCLUSAO] [int] NULL,
	[DT_ULTIMA_ALTERACAO] [datetime] NULL,
	[NR_USUARIO_ALTERACAO] [int] NULL,
	[TP_ALTERA_SENHA] [tinyint] NULL,
	[MOTIVO_DESLIGAMENTO] [varchar](100) NULL,
	[DESLIG_SOLICITANTE] [varchar](50) NULL,
	[DESLIG_AVISO] [int] NULL,
	[TP_OPERACAO] [char](1) NULL,
	[NR_CARTEIRA] [varchar](5) NULL,
	[CD_COMPUTADOR] [tinyint] NULL,
	[CD_SOFTWARE] [tinyint] NULL,
	[CD_INTERNET] [tinyint] NULL,
	[CD_VELOCIDADE_INTERNET] [tinyint] NULL,
	[CD_QTDE_MORADORES] [int] NULL,
	[NM_TEAMS] [varchar](255) NULL,
	[CENTRO_CUSTO] [varchar](200) NULL,
	[NR_ATTO] [bigint] NULL,
	[NR_CODIGO] [bigint] NULL,
	[NR_OLOS_ANT] [bigint] NULL,
	[TP_PRIORIDADE_ACESSO] [int] NULL,
 CONSTRAINT [pk_NR_CPF] PRIMARY KEY CLUSTERED 
(
	[NR_CPF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


